node {
  //stage 'build app'
  //openshiftBuild(namespace: 'default', buildConfig: 'welcome', showBuildLogs: 'true')
  stage 'execute image scan'
    slackSend (color: '#FFFF00', message: "STARTED: Job")

}
